export const ErrorCodes = {
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Auth
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_CREDENTIALS_INVALID: 'AUTH_CREDENTIALS_INVALID',

  // Resources
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_FORBIDDEN: 'RESOURCE_FORBIDDEN',

  // Business
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  INSUFFICIENT_INVENTORY: 'INSUFFICIENT_INVENTORY',
  DUPLICATE_OPERATION: 'DUPLICATE_OPERATION',

  // Payment
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',

  // Database
  QUERY_FAILED: 'QUERY_FAILED',
  UNIQUE_CONSTRAINT_VIOLATION: 'UNIQUE_CONSTRAINT_VIOLATION',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',

  // PII / Security
  PII_ENCRYPTION_FAILED: 'PII_ENCRYPTION_FAILED',
  PII_DECRYPTION_FAILED: 'PII_DECRYPTION_FAILED',
  API_KEY_INVALID: 'API_KEY_INVALID',
  IDEMPOTENCY_REPLAY: 'IDEMPOTENCY_REPLAY',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
